### PR TITLE
Add IPv6 support

### PR DESCRIPTION
**Pull request by yassernasc**
Along with the feature implementation, there is a refactor about how we deal with multiple argument schemas, my goals were easy scalability/adaptation, and don't repeat the default values; as a downside, the code became a bit verbose.

About the IPv6 feature, I added a very simple heuristic to detect which family the host belongs: `const family = host.includes(':') ? 6 : 4`, and IDK if it's the recommended way or good enough.

The new unit test was tested on node.js as well.

### CODE REVIEW

**Review by kasperisager — CHANGES_REQUESTED** [review]
The IPv6 bit is solid! Let's go back to the explicit argument shuffling though instead of adding an indirection. Argument shuffling is an ingrained part of overloaded functions and so should be colocated with the function rather than indirected.

**Comment by kasperisager** [comment]
Let's actually also grab the IP family predicates from https://github.com/holepunchto/udx-native/blob/main/lib/ip.js so the detection becomes rock solid.

**Comment by yassernasc** [comment]
Alright, also added a new error handling for the case where `ip.isIP` function returns 0.

**Review by kasperisager — APPROVED** [review]
Looks fantastic! 👏

**Pull request merged**
